//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public string ApplicationTitle { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> CreatationDate { get; set; }
        public int isDeleted { get; set; }
        public Nullable<int> AppCategoryId { get; set; }
        public int UserId { get; set; }
        public string Allignment { get; set; }
        public string Tags { get; set; }
    
        public virtual ApplicationCategory ApplicationCategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
