//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCategory
    {
        public ApplicationCategory()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int ApplicationCategoryId { get; set; }
        public string Title { get; set; }
        public int isDeleted { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
    }
}
