//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public System.DateTime CreatationDate { get; set; }
        public string PostSubject { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public string PostLink { get; set; }
        public int UserId { get; set; }
        public int isDeleted { get; set; }
        public int PostCategoryId { get; set; }
        public string Allignment { get; set; }
        public string Tags { get; set; }
    
        public virtual PostCategory PostCategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
