//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCategory
    {
        public PostCategory()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryTitle { get; set; }
        public Nullable<int> isDeleted { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
