//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentData
    {
        public int RecentDataId { get; set; }
        public Nullable<int> userId { get; set; }
        public string PagesLinks { get; set; }
        public string PostsLinks { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
