//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELORG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Applications = new HashSet<Application>();
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
            this.RecentDatas = new HashSet<RecentData>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ActivationKey { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<RecentData> RecentDatas { get; set; }
    }
}
